
export const LUCKY_LOTTERY_ABI = [
  "function buyLink() external",
  "function convertLink() external",
  "function topUpSubscription() external",
  "function maintainLink() external",
  "function unwrapAllWBNB() external returns (uint256)",
  "function convertAllLinkToErc677() external returns (uint256)",
  "function register() external",
  "function unregister() external",
  "function claimPendingReward() external",
  "function recycleStuckPending(address user) external",
  "function triggerKoi() external returns (uint8 status, bool triggered)",
  "function triggerKoiStrict() external",
  "function cleanup(uint256 maxIterations) external returns (uint256 processed, uint256 removed)",
  "function reportInvalid(address holder) external",
  "function cancelStuckKoi() external",
  "function canTriggerKoi() external view returns (bool)",
  "function checkTriggerStatus() external view returns (uint8 status, bool canTrigger)",
  "function calculateGasReward() external view returns (uint256)",
  "function getKoiPool() external view returns (uint256)",
  "function getActualKoiPool() external view returns (uint256)",
  "function getMinPossibleReward() external view returns (uint256)",
  "function isPoolSufficient() external view returns (bool)",
  "function getContractLinkBalance() external view returns (uint256)",
  "function getContractBep20LinkBalance() external view returns (uint256)",
  "function getSubscriptionBalance() external view returns (uint96)",
  "function getTotalLinkBalance() external view returns (uint256)",
  "function getErc677LinkBalance() external view returns (uint256)",
  "function getHolderCount() external view returns (uint256)",
  "function getMaxHolders() external view returns (uint256)",
  "function getCurrentEpoch() external view returns (uint256)",
  "function isHolder(address addr) external view returns (bool)",
  "function isTokenLocked() external view returns (bool)",
  "function isOwnershipRenounced() external view returns (bool)",
  "function isAdminRenounced() external view returns (bool)",
  "function getInterval() external view returns (uint256)",
  "function getAdmin() external view returns (address)",
  "function getCallbackGasLimit() external view returns (uint32)",
  "function getKoiFailedCount() external view returns (uint256)",
  "function needsLinkPurchase() external view returns (bool)",
  "function needsLinkConversion() external view returns (bool)",
  "function hasLinkToTopUp() external view returns (bool)",
  "function previewGasReward() external view returns (uint256 reward, bool canTrig, uint256 pool)",
  "function getTriggerStatusDetails() external view returns (uint8 status, bool canTrig, uint256 timeUntilNext, uint256 currentPool, uint256 minReward, uint256 holderCnt, uint256 linkBal)",
  "function getContractStats() external view returns (uint256 holderCnt, uint256 pool, uint256 nextTime, uint256 lotteries, uint256 rewards, uint256 pendingTotal, bool canTrig, bool inProg)",
  "function getPoolStats() external view returns (uint256 pool, uint256 minReward, uint256 maxReward, uint256 minRequired, bool sufficient)",
  "function getGasRewardStats() external view returns (uint256 total, uint256 current, uint256 base, uint256 max)",
  "function getTriggerStats() external view returns (uint256 attempts, uint256 skipped, uint256 failed, uint256 successRate)",
  "function getKoiCountdown() external view returns (uint256 remaining, uint256 nextTime, bool canTrig)",
  "function getLinkStats() external view returns (uint256 erc677Bal, uint256 bep20Bal, uint96 subBal, uint256 totalBal, uint256 availEth, bool needsBuy, bool needsConvert, bool hasTopUp, uint256 purchased, uint256 spent, uint256 received)",
  "function getUserInfo(address user) external view returns (bool registered, uint256 balance, uint256 rewardPct, bool valid, uint256 won, uint256 winCnt, uint256 pendingAmt)",
  "function getUserTriggerInfo(address user) external view returns (uint256 triggers, uint256 gasRewards, uint256 attempts, uint256 donations)",
  "function getOwnershipInfo() external view returns (address currentOwner, address admin, bool ownerRenounced, bool adminRenounced, bool tokenIsLocked)",
  "function getConfig() external view returns (address tokenAddr, address link677Addr, address linkBep20Addr, address pegSwapAddr, address routerAddr, address wbnbAddr, uint256 minHold, uint256 fullHold, uint256 koiInterval, uint256 maxH, uint32 gasLimit, bool tokenIsSet, bool tokenIsLocked, address admin, bool ownershipRenounced, bool adminRenounced)",
  "function previewRewardPercentage(uint256 balance) external view returns (uint256)",
  "function getPendingDetails(address user) external view returns (uint256 amount, uint256 since, bool canRecycle, uint256 recycleTime)",
  "function getCleanupProgress() external view returns (uint256 idx, uint256 total, uint256 remaining, uint256 pct)",
  "function getHolders(uint256 start, uint256 count) external view returns (address[])",
  "function getAdminConfigLimits() external view returns (uint256 minMaxHolders, uint256 maxMaxHolders, uint32 minCallbackGas, uint32 maxCallbackGas, uint256 minIntervalLimit, uint256 maxIntervalLimit)",
  "event Registered(address indexed holder, uint256 balance, uint256 epoch)",
  "event Unregistered(address indexed holder)",
  "event InvalidRemoved(address indexed holder)",
  "event KoiTriggered(uint256 indexed reqId, address indexed triggeredBy)",
  "event KoiTriggerSkipped(address indexed user, uint8 indexed status)",
  "event WinnerSelected(uint256 indexed reqId, address indexed winner, uint256 reward, uint256 pct)",
  "event RewardSent(address indexed winner, uint256 amount)",
  "event RewardPending(address indexed winner, uint256 amount)",
  "event RewardClaimed(address indexed user, uint256 amount)",
  "event KoiFailed(uint256 indexed reqId, string reason)",
  "event LinkPurchased(uint256 ethSpent, uint256 linkReceived)",
  "event LinkSwapped(uint256 bep20Amount, uint256 erc677Amount)",
  "event LinkReceived(address indexed from, uint256 amount)",
  "event LinkTopUp(uint256 amount)",
  "event LinkTopUpFailed(uint256 amount)",
  "event SwapFailed()",
  "event PegSwapFailed(uint256 amount)",
  "event WBNBRecovered(uint256 amount)",
  "event TokenSet(address indexed tokenAddress, uint256 minHolding, uint256 fullHolding, uint256 epoch)",
  "event TokenLockEvent(address indexed tokenAddress)",
  "event HoldingRequirementsUpdated(uint256 oldMin, uint256 newMin, uint256 oldFull, uint256 newFull)",
  "event IntervalUpdated(uint256 oldInterval, uint256 newInterval)",
  "event MaxHoldersUpdated(uint256 oldMaxHolders, uint256 newMaxHolders)",
  "event CallbackGasLimitUpdated(uint32 oldGasLimit, uint32 newGasLimit)",
  "event OwnershipRenounced(address indexed previousOwner)",
  "event AdminRenounced(address indexed previousAdmin)",
  "event CleanupProgress(uint256 processed, uint256 remaining, uint256 removed)",
  "event PendingRecycled(address indexed user, uint256 amount)",
  "event GasRewardSent(address indexed trigger, uint256 amount)",
  "event GasRewardFailed(address indexed trigger, uint256 amount)",
  "event EpochIncremented(uint256 oldEpoch, uint256 newEpoch)"
];

export const ERC20_ABI = [
  "function balanceOf(address owner) view returns (uint256)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function transfer(address to, uint256 amount) external returns (bool)"
];
